const CrudActionTypes = {
  DASHBOARD_NEW_ITEM: "DASHBOARD_NEW_ITEM",
  DASHBOARD_NEW_ITEM_SUCCESS: "DASHBOARD_NEW_ITEM_SUCCESS",
  DASHBOARD_NEW_ITEM_FAILURE: "DASHBOARD_NEW_ITEM_FAILURE",
  DASHBOARD_UPDATE_ITEM: "DASHBOARD_UPDATE_ITEM",
  DASHBOARD_UPDATE_ITEM_SUCCESS: "DASHBOARD_UPDATE_ITEM_SUCCESS",
  DASHBOARD_UPDATE_ITEM_FAILURE: "DASHBOARD_UPDATE_ITEM_FAILURE",
  DASHBOARD_DELETE_ITEM: "DASHBOARD_DELETE_ITEM",
  DASHBOARD_DELETE_ITEM_SUCCESS: "DASHBOARD_DELETE_ITEM_SUCCESS",
  DASHBOARD_DELETE_ITEM_FAILURE: "DASHBOARD_DELETE_ITEM_FAILURE",
  NEW_CHAMPIONSHIP: "NEW_CHAMPIONSHIP",
  NEW_CHAMPIONSHIP_SUCCESS: "NEW_CHAMPIONSHIP_SUCCESS",
  NEW_CHAMPIONSHIP_FAILURE: "NEW_CHAMPIONSHIP_FAILURE",
  UPDATE_CHAMPIONSHIP: "UPDATE_CHAMPIONSHIP",
  UPDATE_CHAMPIONSHIP_SUCCESS: "UPDATE_CHAMPIONSHIP_SUCCESS",
  UPDATE_CHAMPIONSHIP_FAILURE: "UPDATE_CHAMPIONSHIP_FAILURE",
  DELETE_CHAMPIONSHIP: "DELETE_CHAMPIONSHIP",
  DELETE_CHAMPIONSHIP_SUCCESS: "DELETE_CHAMPIONSHIP_SUCCESS",
  DELETE_CHAMPIONSHIP_FAILURE: "DELETE_CHAMPIONSHIP_FAILURE",
};

export default CrudActionTypes;
