const CrudActionTypes = {
  DASHBOARD_NEW_ITEM: "DASHBOARD_NEW_ITEM",
  DASHBOARD_NEW_ITEM_SUCCESS: "DASHBOARD_NEW_ITEM_SUCCESS",
  DASHBOARD_NEW_ITEM_FAILURE: "DASHBOARD_NEW_ITEM_FAILURE",
  DASHBOARD_UPDATE_ITEM: "DASHBOARD_UPDATE_ITEM",
  DASHBOARD_UPDATE_ITEM_SUCCESS: "DASHBOARD_UPDATE_ITEM_SUCCESS",
  DASHBOARD_UPDATE_ITEM_FAILURE: "DASHBOARD_UPDATE_ITEM_FAILURE",
  DASHBOARD_DELETE_ITEM: "DASHBOARD_DELETE_ITEM",
  DASHBOARD_DELETE_ITEM_SUCCESS: "DASHBOARD_DELETE_ITEM_SUCCESS",
  DASHBOARD_DELETE_ITEM_FAILURE: "DASHBOARD_DELETE_ITEM_FAILURE",
};

export default CrudActionTypes;
