const UiActionTypes = {
  FETCH_UI_DATA_START: "FETCH_UI_DATA_START",
  FETCH_UI_DATA_SUCCESS: "FETCH_UI_DATA_SUCCESS",
  FETCH_UI_DATA_FAILURE: "FETCH_UI_DATA_FAILURE",
  UI_NEW_UPDATE_ITEM: "UI_NEW_UPDATE_ITEM",
  UI_DELETE_ITEM: "UI_DELETE_ITEM",
  UI_NEW_SUBITEM: "UI_NEW_SUBITEM",
  UI_UPDATE_SERIES: "UI_UPDATE_SERIES",
};

export default UiActionTypes;
