const UiActionTypes = {
  LOAD_UI_DATA_START: "LOAD_UI_DATA_START",
  LOAD_UI_DATA_SUCCESS: "LOAD_UI_DATA_SUCCESS",
  LOAD_UI_DATA_FAILURE: "LOAD_UI_DATA_FAILURE",
  SUBMIT_NEW_ITEM: "SUBMIT_NEW_ITEM",
  SUBMIT_NEW_ITEM_SUCCESS: "SUBMIT_NEW_ITEM_SUCCESS",
  SUBMIT_NEW_ITEM_FAILURE: "SUBMIT_NEW_ITEM_FAILURE",
};

export default UiActionTypes;
