const UiActionTypes = {
  FETCH_UI_DATA_START: "FETCH_UI_DATA_START",
  FETCH_UI_DATA_SUCCESS: "FETCH_UI_DATA_SUCCESS",
  FETCH_UI_DATA_FAILURE: "FETCH_UI_DATA_FAILURE",
};

export default UiActionTypes;
